openapi: 3.0.0
info:
  title: Currency Converter API
  version: 1.0.0
paths:
  /currencies:
    get:
      summary: Get supported currencies
      responses:
        '200':
          description: A list of supported currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /convert:
    post:
      summary: Convert amount between currencies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_currency:
                  type: string
                to_currency:
                  type: string
                amount:
                  type: number
              required:
                - from_currency
                - to_currency
                - amount
      responses:
        '200':
          description: Conversion result
          content:
            application/json:
              schema:
                type: object
                properties:
                  converted:
                    type: number
