openapi: 3.0.0
info:
  title: Currency Converter API
  version: 1.0.0
  description: |
    API для конвертации валют. Позволяет получить список поддерживаемых валют, выполнить конвертацию суммы из одной валюты в другую, а также получить список доступных дат.
  contact:
    name: GitHub Currency Converter
    url: https://github.com/ExtroZ-ui/Converter/tree/master

servers:
  - url: http://localhost:8000
    description: Локальный сервер
  - url: https://converter-cpgc.onrender.com
    description: Временный сервер

tags:
  - name: Currencies
    description: Работа с валютами
  - name: Conversion
    description: Конвертация валют

paths:
  /currencies:
    get:
      tags:
        - Currencies
      summary: Получить список поддерживаемых валют
      description: Возвращает массив строк с кодами поддерживаемых валют.
      responses:
        '200':
          description: Успешный ответ с массивом валют
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - USD
                - EUR
                - RUB
                - JPY
                - GBP

  /currencies/{from}/{to}:
    get:
      tags:
        - Conversion
      summary: Конвертация суммы между валютами
      description: |
        Выполняет конвертацию указанной суммы из одной валюты в другую.
        Валюты передаются в виде path-параметров (`from`, `to`), сумма — в query (`amount`), дата — опционально.
      parameters:
        - name: from
          in: path
          required: true
          schema:
            type: string
          description: Код валюты источника (например, RUB)
          example: RUB
        - name: to
          in: path
          required: true
          schema:
            type: string
          description: Код валюты назначения (например, USD)
          example: USD
        - name: amount
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Сумма для конвертации
          example: 100.50
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Дата курса в формате YYYY-MM-DD (если не указана, используется последний)
          example: "2024-01-15"

      responses:
        '200':
          description: Результат конвертации
          content:
            application/json:
              schema:
                type: object
                properties:
                  from:
                    type: string
                    description: Валюта источника
                    example: RUB
                  to:
                    type: string
                    description: Валюта назначения
                    example: USD
                  amount:
                    type: number
                    description: Исходная сумма
                    example: 100.5
                  result:
                    type: number
                    description: Конвертированная сумма
                    example: 1.1
                  date:
                    type: string
                    format: date
                    description: Использованная дата курса
                    example: "2024-01-15"
        '400':
          description: Ошибка в параметрах запроса
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Некорректные параметры запроса"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Ошибка на сервере"

  /available-dates:
    get:
      tags:
        - Currencies
      summary: Получить список доступных дат курсов валют
      description: Возвращает массив дат, для которых доступны валютные курсы.
      responses:
        '200':
          description: Успешный ответ с массивом дат
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: date
              example:
                - "2024-01-01"
                - "2024-01-02"
                - "2024-01-03"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Внутренняя ошибка сервера при получении доступных дат."
